name: Deploy 'nearbuilders-delegation' Components to Mainnet

on:
  push:
    branches: [main]

jobs:
  deploy-mainnet:
    runs-on: ubuntu-latest
    environment: buildcommons.near
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to mainnet
        uses: nearbuilders/bos-workspace/.github/workflows/deploy.yml@main
        with:
          bw-legacy: false
          deploy-env: "mainnet"
          app-name: "nearbuilders-delegation"
          deploy-account-address: ${{ secrets.BOS_DEPLOY_ACCOUNT_ID }}
          signer-account-address: ${{ secrets.BOS_DEPLOY_ACCOUNT_ID }}
          signer-public-key: ${{ secrets.BOS_SIGNER_PUBLIC_KEY }}
        env:
          SIGNER_PRIVATE_KEY: ${{ secrets.BOS_SIGNER_PRIVATE_KEY }}
