name: Deploy 'nearbuilders-delegation' Components to Mainnet

on:
  push:
    branches: [main]

jobs:
  deploy-mainnet:
    uses: nearbuilders/bos-workspace/.github/workflows/deploy.yml@main
    with:
      bw-legacy: false
      deploy-env: "mainnet"
      app-name: "nearbuilders-delegation"
      deploy-account-address: "buildcommons.near"
      signer-account-address: "buildcommons.near"
      signer-public-key: "ed25519:BDD3c71kFuzD4jUtZcYyjEwhKjpvecH21zYSqinLXi15"
    secrets:
      SIGNER_PRIVATE_KEY: ${{ secrets.BOS_SIGNER_PRIVATE_KEY }}
