name: Deploy web4 to production
on:
  push:
    branches: [main]
    paths:
      - public/**

jobs:
  deploy-web4:
    name: Deploy web4 to production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy to web4
        run: |
          NEAR_SIGNER_KEY="${{ secrets.BOS_SIGNER_PRIVATE_KEY }}" npx github:elliotBraem/web4-deploy#fix/update-min-contract public buildcommons.near --deploy-contract --nearfs
