name: Deploy to production
on:
  push:
    branches: [main]
    paths:
      - web4contract/**

defaults:
  run:
    working-directory: ./web4contract

jobs:
  test:
    uses: ./.github/workflows/web4-test.yml

  deploy-staging:
    name: Deploy to production
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install cargo-near CLI
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/near/cargo-near/releases/download/cargo-near-v0.6.2/cargo-near-installer.sh | sh
      - name: Deploy to production
        run: |
          cargo near deploy "buildcommons.near" \
            without-init-call \
            network-config "mainnet" \
            sign-with-plaintext-private-key \
              --signer-public-key "ed25519:BDD3c71kFuzD4jUtZcYyjEwhKjpvecH21zYSqinLXi15" \
              --signer-private-key "${{ secrets.BOS_SIGNER_PRIVATE_KEY }}" \
            send
